# Copyright 2023 Dimitri Koshkin. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: build-on-macos

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-run:
    runs-on: macos-latest
    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          brew: bash coreutils findutils

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install tools via asdf
        uses: asdf-vm/actions/install@v2.2.0
        with:
          asdf_branch: v0.11.2

      - name: Build
        run: make SKIP_UPX=false build-snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run binary
        run: |
          ./dist/seed_darwin_amd64_v1/seed --version
