# Copyright 2025 Dimitri Koshkin. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Conventional Release Labels

on:
  pull_request:
    types:
      - opened
      - edited
jobs:
  label:
    runs-on: ubuntu-24.04
    steps:
      - uses: bcoe/conventional-release-labels@v1
