# Copyright 2025 Dimitri Koshkin. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: E2E Tests

on:
  workflow_call:
    inputs:
      skip:
        description: e2e tests to skip
        type: string
      focus:
        description: e2e tests to focus
        type: string

jobs:
  e2e-test:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      checks: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.13.0
        with:
          enable-cache: true

      - name: Go cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # The default disk size of Github hosted runners is ~14GB, this is not enough to run the e2e tests.
      # Cleanup the disk, see upstream discussion https://github.com/actions/runner-images/issues/2840.
      - name: Cleanup Disk Space
        run: |
          echo "Before removing files:"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          echo "After removing files:"
          df -h

      - name: Run e2e tests
        run: devbox run -- make e2e-test E2E_SKIP='${{ inputs.skip }}' E2E_FOCUS='${{ inputs.focus }}' E2E_VERBOSE=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - if: success() || failure() # always run even if the previous step fails
      #   name: Publish e2e test report
      #   uses: mikepenz/action-junit-report@v5
      #   with:
      #     report_paths: 'junit-e2e.xml'
      #     check_name: 'e2e test report'
      #     detailed_summary: true
      #     require_passed_tests: true
