# Copyright 2025 Dimitri Koshkin. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Govulncheck

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

defaults:
  run:
    shell: bash
jobs:
  govulncheck:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        module: [.]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.13.0
        with:
          enable-cache: true

      - id: govulncheck
        run: devbox run -- make govulncheck.${{ matrix.module }}
