# Copyright 2025 Dimitri Koshkin. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: release-please

on:
  push:
    branches:
      - main
      - release/v*

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write

defaults:
  run:
    shell: bash

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          target-branch: ${{ github.ref_name }}

      - uses: actions/checkout@v4
        if: ${{ steps.release-please.outputs.release_created }}

      - if: ${{ steps.release-please.outputs.release_created }}
        name: Run release workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: release.yml
          ref: ${{ steps.release-please.outputs.tag_name }}
